version: 0.2

env:
  variables:
    REVISION_ID: ${CODEBUILD_RESOLVED_SOURCE_VERSION}

phases:
  build:
    commands:
      - env
      - echo Build started on `date`
      - make init
      - make functional
      - aws s3 cp ./report.html s3://gaurav-pytest-html-test-report/  
artifacts:
  files:
    - '**/*'
