version: 0.2

env:
  variables:
    REVISION_ID: ${CODEBUILD_RESOLVED_SOURCE_VERSION}

phases:
  pre_build:
    commands:
      - env
      - echo Build started on `date`
      - make functional
artifacts:
  files:
    - '**/*'
